import Link from 'next/link'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home' },
  { href: '/docs', label: 'Docs' },
  { href: '/todos', label: 'Todos' },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 font-mono font-bold`}>
        <StyledComponentsRegistry>
          <header className="p-4 font-mono bg-gray-100">
            <nav className="flex justify-center">
              <ul className="flex items-center gap-8">
                {links.map((link) => (
                  <li key={link.href}>
                    <Link href={link.href}>{link.label}</Link>
                  </li>
                ))}
              </ul>
            </nav>
          </header>
          <main className="p-4 font-mono">{children}</main>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
